###consul服务端口号
server:
  port: 81

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.160.10
      port: 8500
      discovery:
        hostname: 192.168.43.81
        service-name: ${spring.application.name}

