server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.160.10:8849 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


